# -*- coding: utf-8 -*-
"""assess1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_DaE8oHUoqxb75lNqTZRBOzTtbpPzYF

Q1
"""

length=int(input("Enter the length in meters:"))
width=int(input("Enter the width in meters:"))
area = length*width

if area >= 100000:
  print("Large")
elif area >=500000 and area < 100000:
  print("Medium")
else:
  print("Small")

"""Q2"""

def obese():
  print("Eat protein and less calories and cut carbs")
  print("Move more, Track your calories")

def fit():
  print("Maintain your diet")
  print("Do exercise , balance your meals")

def underweight():
  print("Eat more protein and carbs")
  print("Increase calorie intake, do strength training")

weight=int(input("Enter the weight:"))
height=float(input("Enter the height:"))

bmi =weight/pow(height,2)
print(bmi)

if bmi >= 2:
  print("Obese")
  print(obese())
elif bmi<2.5 and bmi>=-2.5:
  print("Fit")
  print(fit())
else:
  print("Underweight")
  print(underweight())

"""  Q3"""

def student1():
  dict1={'Math':97,'Science':85,'Csc':92}
  print("Student 1:",dict1)
def add(dict1):
  add = dict1.update({"History":75,"Geo":83})
  print(add)

def student2():
  dict2={'Math':87,'Science':90,'Csc':95}
  print("Student 2:",dict2)

student1()
student2()

"""Q4"""

def child():
  print("Cartoon Shows")
  print("Tangled, Ben 10")

def teen():
  print("100, The vampire diaries")
  print("Vikram, Tranformers, Fault in our stars")

def senior():
  print("Dhoordharson")
  print("mgr movies, Sivaji movies")

def adult():
  print("news channel, Friends, office")
  print("Vikram, Leo, Avesha")

age=int(input("Enter the age:"))

if age >= 50:
  print("Senior")
  print(senior())
elif age<50 and age>=21:
  print("Adult")
  print(adult())
elif age< 21 and age >=13:
  print("Teen")
  print(teen())
else:
  print("Children")
  print(child())

"""  Q5"""

list1 = [13,5,7,834,846,73,58,23,51]

for i in list1:
  list2=[]
  if(i%2==0):
    x=i
    list2.append(x)
    i=i+1
    print(list2)

"""Q6"""

password = "qsuty@win2023"

while True:
  pow = input("Enter the password:")
  if(pow==password):
    print("Correct Password")
    break
  else:
    print("Wrong password")
    i+1

"""  Q7"""

def satisfac(sat):
  print("satisfaction",sat)

def average(score):
  print("average score",score)

satisfac(65)
average(92.9)

"""Q8"""

def vowels():
  strd=input("Enter a comment:")
  sum=0
  for i in strd:
    if i=='a' or i=='e' or i=='i' or i=='o' or i=='u':
      sum = sum+1
  print("Vowels present",sum)

vowels()

"""Q9"""

import datetime
now=datetime.datetime.now()
print(now)

"""Q10"""

savings=int(input("Enter your savings:"))

if 8*7==savings:
  try:
    print("Good savings")
  except:
    print("Wrong division")

"""Q11

Q12
"""

listw =[34,523,22,2,90]
if listw[0]%2==0:
  try:
      print("Divisible")
  except ZeroDivisionError:
    print("Not divisible")

if listw[1]%2==0:
  try:
      print("Divisible")
  except ZeroDivisionError:
    print("Not divisible")

"""Q13"""

with open("C/uploads/report","w") as file:
  file.write("tsdtyd")

"""Q14"""

with open("C/uploads/report","r") as file:
  print(file.read())